### ISSUE TITLE
Create the API based on the OpenAPI documentation

### ISSUE THREAD

**Issue by bidwolf** [bidwolf/alura-courses#113]
# Requirements
- [x] Create a payment transaction following #119 definition
- [x] Get the payment transaction status following the #118 definition
- [x] Get the qrcode image for a required payment transaction following the #120 definition
- [ ] Confirm the payment following the #121 definition
